# Generated by Django 2.0.8 on 2019-01-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contentsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentsource',
            name='source_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
