# Generated by Django 2.2.13 on 2020-06-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200515_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='view_count',
        ),
    ]
