name: Automated tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the project
      uses: actions/checkout@v2
    - name: Start API
      run: docker-compose up --build -d
    - name: Wait for API to come up
      run: bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8000/healthcheck)" != "200" ]]; do sleep 10; done'
    - name: Load test data
      run: ./load_sample_data.sh
    - name: Wait for data to be loaded
      run: bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8000/v1/images?q=test)" != "200" ]]; do sleep 5; done'
    - name: Run API tests
      run: cd cccatalog-api && test/run_test.sh
